spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        jdbc: trace

jwt:
  expiration: 3600000
  secret: tM3v#p8^UDW$wR+5$U5$TZFXIe2rZ{}GV73&(16iKKTwJA}U;g
